# Generated by Django 3.2 on 2022-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(default='images/one.jpg', upload_to='images/'),
        ),
    ]
