# Generated by Django 3.2 on 2022-02-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(default='images/one.jpg', upload_to='media/images/'),
        ),
    ]
